pipeline {
    agent any
    stages {
        stage('clean') { 
            steps { 
               echo 'This is a minimal pipeline.' 
                sh 'mvn --version'
                sh "/opt/tools/apache-maven-3.6.2/bin/mvn -f maven/pom.xml clean test"
            }
        }
        stage('Build') { 
            steps { 
               echo 'This is a minimal pipeline.' 
            }
        }
       
    }
    post {
        always {
            echo 'I have finished and deleting workspace'
            deleteDir() 
        }
        success {
            echo 'Job succeeeded!'
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'I failed :('
        }
        changed {
            echo 'Things were different before...'
        }
    }
}
